# Generated by Django 4.2.1 on 2023-06-13 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='availabilty',
            new_name='availability',
        ),
        migrations.AddConstraint(
            model_name='reservation',
            constraint=models.UniqueConstraint(fields=('user', 'start_date', 'end_date'), name='user_rent_date'),
        ),
    ]
